# Generated by Django 5.2.1 on 2025-07-18 02:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0002_adding_base_models"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="member",
            name="status",
            field=models.CharField(choices=[("CRT", "Current"), ("GRD", "Graduated")], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name="member",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name="member",
            name="role",
            field=models.CharField(choices=[("PHD", "Phd Student"), ("MSC", "M Student"), ("PRO", "Professor")], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name="member",
            name="user",
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
