# Generated by Django 5.2.1 on 2025-07-19 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0003_updating_member"),
    ]

    operations = [
        migrations.AddField(
            model_name="award",
            name="organization",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="award",
            name="year",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
