# Generated by Django 5.2.1 on 2025-07-21 13:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("backend", "0004_awards_year_org"),
    ]

    operations = [
        migrations.AddField(
            model_name="researchproject",
            name="github_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="researchproject",
            name="leader",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="backend.member"),
        ),
        migrations.AddField(
            model_name="researchproject",
            name="project_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
