# Generated by Django 5.2.1 on 2025-07-27 01:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0006_add_course_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="capacity",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="event",
            name="location",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="event",
            name="registration_url",
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name="event",
            name="speaker",
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to="backend.member"),
        ),
        migrations.AddField(
            model_name="event",
            name="time",
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name="event",
            name="date",
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name="event",
            name="description",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="event",
            name="domain",
            field=models.CharField(
                choices=[
                    ("SMN", "seminar"),
                    ("WRK", "workshop"),
                    ("CNF", "conference"),
                    ("DFN", "defense"),
                    ("MTG", "meeting"),
                    ("CLL", "colloquium"),
                    ("MST", "masterclass"),
                ],
                max_length=3,
                null=True,
            ),
        ),
    ]
