# Generated by Django 5.2.1 on 2025-07-27 01:36

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0007_change_fields_event"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="tags",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=50), blank=True, default=list, null=True, size=None
            ),
        ),
    ]
