# Generated by Django 5.2.1 on 2025-08-07 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0008_adding_tags_to_event"),
    ]

    operations = [
        migrations.AddField(
            model_name="member",
            name="dblp_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="member",
            name="google_scholar_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="member",
            name="stackoverflow_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="member",
            name="twitter_x_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
