# Generated by Django 5.2.1 on 2025-08-11 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0009_member_dblp_url_member_google_scholar_url_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Invitation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("email", models.EmailField(max_length=254)),
                ("role", models.CharField(max_length=50)),
                ("token", models.CharField(default="14f8d86717184d64a54aa962dedc71cd", max_length=64, unique=True)),
                ("sent_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
                (
                    "status",
                    models.CharField(
                        choices=[("pending", "Pending"), ("expired", "Expired"), ("registered", "Registered"), ("canceled", "Canceled")],
                        default="pending",
                        max_length=10,
                    ),
                ),
            ],
        ),
    ]
