services:
    frontend:
        build:
            context: .
            dockerfile: src/DOCKERFILE
        ports:
            - "5173:5173"
        volumes:
            - ./src:/app/src
            - ./package.json:/app/package.json
            - ./package-lock.json:/app/package-lock.json
            - ./vite.config.mts:/app/vite.config.mts
            - ./tsconfig.json:/app/tsconfig.json
            - ./tailwind.config.js:/app/tailwind.config.js
            - ./postcss.config.js:/app/postcss.config.js
            - ./index.html:/app/index.html
            - /app/node_modules 
        env_file:
            - .env
        command: npm run dev -- --host "0.0.0.0"
    backend:
        build:
            context: .
            dockerfile: backend/DOCKERFILE
        command: python manage.py runserver 0.0.0.0:8000
        ports:
            - "8000:8000"
        volumes:
            - ./backend:/app
        env_file:
            - .env
        depends_on:
            - db
    db:
        image: postgres:17.5
        container_name: postgres
        restart: always
        environment:
            POSTGRES_USER: ${DB_USER}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
            POSTGRES_DB: postgres
        volumes:
            - postgres_data:/var/lib/postgresql/data
        ports:
            - "5432:5432"

    pgadmin:
        image: dpage/pgadmin4
        container_name: pgadmin
        restart: always
        environment:
            PGADMIN_DEFAULT_EMAIL: admin@admin.com
            PGADMIN_DEFAULT_PASSWORD: admin123
        ports:
            - "5050:80"
        depends_on:
            - db

    mailhog:
        image: mailhog/mailhog
        container_name: mailhog
        ports:
        - "1025:1025"  # SMTP port
        - "8025:8025"  # Web UI port:

volumes:
    postgres_data:
