FROM python:3.13-alpine

WORKDIR /app

COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

# To run pytest
COPY .coveragerc .coveragerc

COPY backend/ .

CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]