@startuml
!define RECTANGLE class

title STIL overview architecture

node "Render" {
    node "Backend" as BE {
        component "Django REST API" as Django
    }
    node "Frontend" as FE {
        component "Vue.js\nTailwindCSS" as Vue
    }

    database "PostgreSQL Database" as DB
}

Vue --> Django : HTTP Request\n(Axios / Fetch)
Django --> DB : SQL Request\n(ORM Django)

@enduml
