name: Backend CI pipeline

on:
    push:
        branches: ["**"]
    pull_request:
        branches: ["**"]
    workflow_dispatch:

jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                  python-version: "3.13"
            - name: flake8
              uses: py-actions/flake8@v2

            - name: isort
              uses: isort/isort-action@v1

            - name: black
              uses: psf/black@stable
              with:
                  options: "--check --verbose"

    test:
        runs-on: ubuntu-latest

        services:
            postgres:
                image: postgres:17.5
                env:
                    POSTGRES_USER: postgres
                    POSTGRES_PASSWORD: postgres
                    POSTGRES_DB: test_db
                ports:
                    - 5432:5432
                options: >-
                    --health-cmd pg_isready
                    --health-interval 10s
                    --health-timeout 5s
                    --health-retries 5
        env:
            DB_NAME: test_db
            DB_USER: postgres
            DB_PASSWORD: postgres
            DB_HOST: localhost
            DB_PORT: 5432

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                  python-version: "3.13"

            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install -r requirements.txt

            - name: Run migrations
              run: |
                  python backend/manage.py migrate

            - name: Run tests
              run: |
                  python backend/manage.py test

            # TODO: Pipeline needs to fail if code coverage < 60%
