name: Weekly GetPublications Command Trigger

on:
  schedule:
    - cron: '0 0 * * 1' # Every Monday at midnight

jobs:
  run-command:
    runs-on: ubuntu-latest

    steps:
      - name: Check required secrets
        run: |
          missing=false

          if [ -z "${{ secrets.GITHUB_USERNAME }}" ]; then
            echo "Missing secret: GITHUB_USERNAME"
            missing=true
          fi

          if [ -z "${{ secrets.GITHUB_PASSWORD }}" ]; then
            echo "Missing secret: GITHUB_PASSWORD"
            missing=true
          fi

          if [ -z "${{ secrets.BACKEND_URL }}" ]; then
            echo "Missing secret: BACKEND_URL"
            missing=true
          fi

          if [ "$missing" = true ]; then
            echo "One or more required secrets are missing. Failing the workflow."
            exit 1
          fi

      - name: Run getpublications command
        env:
          GITHUB_USERNAME: ${{ secrets.GITHUB_USERNAME }}
          GITHUB_PASSWORD: ${{ secrets.GITHUB_PASSWORD }}
          BACKEND_URL: ${{ secrets.BACKEND_URL }}
        run: |
          echo "Logging in to $BACKEND_URL/api/login..."

          LOGIN_RESPONSE=$(curl -s -X POST "$BACKEND_URL/api/login" \
            -H "Content-Type: application/json" \
            -d "{\"username_or_email\": \"$GITHUB_USERNAME\", \"password\": \"$GITHUB_PASSWORD\"}")

          ACCESS_TOKEN=$(echo "$LOGIN_RESPONSE" | jq -r '.access_token')

          if [ "$ACCESS_TOKEN" = "null" ] || [ -z "$ACCESS_TOKEN" ]; then
            echo "Login failed or access token missing"
            echo "Response: $LOGIN_RESPONSE"
            exit 1
          fi

          echo "Access token obtained. Sending command..."

          RESPONSE=$(curl -s -w "\n%{http_code}" -X POST "$BACKEND_URL/run-getpublications-command" \
            -H "Authorization: Bearer $ACCESS_TOKEN" \
            -H "Content-Type: application/json")

          HTTP_BODY=$(echo "$RESPONSE" | sed '$d')
          HTTP_STATUS=$(echo "$RESPONSE" | tail -n1) 

          echo "Request response status: $HTTP_STATUS"
          echo "Request response body:"
          echo "$HTTP_BODY"

          if [ "$HTTP_STATUS" -ne 202 ]; then
            echo "Workflow failed"
            exit 1
          fi

